// ARRAY MAP() METHOD
// CREATES A NEW ARRAY POPULATED WITH RESULTS OF CALLING A CALLBACK FUNC ON EVERY ELEMENT IN THE CALLING ARRAY

// CALLBACK FUNCTION IN MAP ACCEPTS SAME ARGUMENTS AS FOR EACH CALLBACK FN, 
// THE CURRENT ELEMENT BEING PROCESSED IN THE ARRAY (VALUE/ITEM), THE INDEX OF CURRENT ELEMENT AND THE ENTIRE ARRAY ON WHICH MAP WAS CALLED.

let myArr = ["one", "two", "three", "four", "five", "six", "seven", "eight"];

// determine length of each str and save it in an array

let strLength = myArr.map(function (item, index, array) {
    return item.length; // RETURNS NEW ARRAY WITH EACH ELEMENT BEING THE RESULT OF THE CALLBACK FUNCTION
});

console.log(strLength);

