// NULL AND UNDEFINED
// BOTH REPRESENT NO VALUE

// UNDEFINED - "JAVASCRIPT CANNOT FIND VALUE FOR THIS"

// VARIABLE WITHOUT VALUE
// MISSING FUNCTION ARGUMENTS
// MISSING OBJECT PROPERTIES

// NULL - DEVELOPER SETS THE VALUE

let num = 20 + null; // 20 + 0;
console.log(num);

let num2 = 20 + undefined; // 20 + 0;
console.log(num2);