// HOISTING
// THE PROCESS OF TAKING TWO PASSES THROUGH THE JS FILE
// FIRST PASS HOISTS ALL DECLARATIONS TO THE TOP OF THE FILE
// FIRST PASS - HOISTS ALL VARIABLES AND FUNCTIONS TO THE TOP, ASSIGNS THEM VALUE OF UNDEFINED



getName(); // WILL RUN EVEN THOUGH BEING INVOKED BEFORE FUNCTION DECLARATION
console.log(x); // RETURNS UNDEFINED
console.log(getName); // LOGS ENTIRE FUNC

var x = 9;

function getName() {
    console.log("hello bye ");
};

// getName(); // INVOKED AFTER FUNCTION DECLARATION
// console.log(x); // VARIABLE HAS ALREADY BEEN DECLARED AND ASSIGNED VALUE ABOVE